### ISSUE TITLE
Is there a reason for ElasticNet and LogitNet models to have different shapes for the coef_ attribute?

### ISSUE THREAD

**Issue by paulhendricks** [civisanalytics/python-glmnet#11]
A minimal, reproducible example:

```python
from glmnet import ElasticNet, LogitNet
from sklearn import datasets

X, y = datasets.make_classification(n_samples=100000, n_features=20,
                                    n_informative=2, n_redundant=2)

er = ElasticNet()
lr = LogitNet()

er.fit(X, y)
print(er.coef_)
print(er.coef_.shape)

lr.fit(X, y)
print(lr.coef_)
print(lr.coef_.shape)
```

**Comment by wlattner** [comment]
Yes, in the binary case, this looks weird, but imagine we have a multinomial problem with 3 classes, then the shape of `coef_` will be (3, n_features). Binary classification is the special case, the shape of `coef_` will be (1, n_features) to keep with the convention followed by Scikit-Learn.

**Comment by paulhendricks** [comment]
Makes sense, thanks for the quick reply!
