### ISSUE TITLE
Docs are not consistent

### ISSUE THREAD

**Issue by beckermr** [civisanalytics/python-glmnet#12]
It looks like the doc strings have slightly different names for various attributes that get set during CV?

**Comment by xdavio** [comment]
I skimmed `logistic.py` and 'linear.py` but nothing popped out at me. If you identify the incorrectly documented attributes, I'll modify the docstrings.

**Comment by beckermr** [comment]
Sorry! Yeah I will add the lines. The differences are small.

**Comment by beckermr** [comment]
Here 

https://github.com/civisanalytics/python-glmnet/blob/master/glmnet/logistic.py#L121

versus here

https://github.com/civisanalytics/python-glmnet/blob/master/glmnet/logistic.py#L158

It looks like the actual attributes are `lambda_max_` and `lambda_best_`.

**Comment by beckermr** [comment]
I would do a search for any instances of the wrong name.

**Comment by xdavio** [comment]
Thanks for catching this @beckermr. Fixed in #14.
