### ISSUE TITLE
Feature request: Poisson regression

### ISSUE THREAD

**Issue by hanfang** [civisanalytics/python-glmnet#13]
Hi,

I came across your implementation. Is it possible to have Poisson regression as well? Do you have plans to include this? Thanks.

**Comment by wlattner** [comment]
We're currently working on it!

**Comment by hanfang** [comment]
Hi @wlattner, not trying to push here. But just wondering if you have an ETA on this? This would be super useful. Thanks in advance.

**Comment by hanfang** [comment]
Hi @wlattner , let me know if you can use any help implement this . Thanks.
