### ISSUE TITLE
Custom Cross-validation scheme

### ISSUE THREAD

**Issue by oliverangelil** [civisanalytics/python-glmnet#21]
Is it possible to customise the CV scheme? For example, can one perform [canonical CV](https://stats.stackexchange.com/a/14107/134691)?

**Comment by kcrum** [comment]
Sorry for the nearly year-late response! If you clone this repo and install from source, you can change your CV scheme on `ElasticNet` or `LogitNet` by accessing the `CV` attribute prior to fitting:

```python
import glmnet
en = glmnet.ElasticNet()
en.CV = <an sklearn-compatible CV generator>
```

Unfortunately, if you were to install from PyPI (i.e. via `pip`) right now, you wouldn't be able to change your CV generator. This will be available whenever we tag the next version.
