### ISSUE TITLE
Math domain error when fitting a model

### ISSUE THREAD

**Issue by Visdoom** [civisanalytics/python-glmnet#27]
Hey there, 
I sometimes get the following error when fitting the model for cross validation:

```
ValueError                                Traceback (most recent call last)
<ipython-input-39-ed9d5b075d90> in <module>()
     38         print(X_train.shape)
     39 
---> 40     m.fit(X_train,y_train)
     41     scores.append(m.score(X_test,y_test))
     42 

/usr/local/lib/python3.5/dist-packages/glmnet/logistic.py in fit(self, X, y, sample_weight, relative_penalties)
    196                                            self.scoring, classifier=True,
    197                                            n_jobs=self.n_jobs,
--> 198                                            verbose=self.verbose)
    199 
    200             self.cv_mean_score_ = np.atleast_1d(np.mean(cv_scores, axis=0))

/usr/local/lib/python3.5/dist-packages/glmnet/util.py in _score_lambda_path(est, X, y, sample_weight, relative_penalties, cv, scoring, classifier, n_jobs, verbose)
     69             delayed(_fit_and_score)(est, scorer, X, y, sample_weight, relative_penalties,
     70                                     est.lambda_path_, train_idx, test_idx)
---> 71             for (train_idx, test_idx) in cv)
     72 
     73     return scores

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

/usr/local/lib/python3.5/dist-packages/glmnet/util.py in _fit_and_score(est, scorer, X, y, sample_weight, relative_penalties, score_lambda_path, train_inx, test_inx)
    112     """
    113     m = clone(est)
--> 114     m = m._fit(X[train_inx, :], y[train_inx], sample_weight[train_inx], relative_penalties)
    115 
    116     lamb = np.clip(score_lambda_path, m.lambda_path_[-1], m.lambda_path_[0])

/usr/local/lib/python3.5/dist-packages/glmnet/logistic.py in _fit(self, X, y, sample_weight, relative_penalties)
    370         self.lambda_path_ = self.lambda_path_[:self.n_lambda_]
    371         # also fix the first value of lambda
--> 372         self.lambda_path_ = _fix_lambda_path(self.lambda_path_)
    373         self.intercept_path_ = self.intercept_path_[:, :self.n_lambda_]
    374         # also trim the compressed coefficient matrix

/usr/local/lib/python3.5/dist-packages/glmnet/util.py in _fix_lambda_path(lambda_path)
    122     reasonable. The method below matches what is done in the R/glmnent wrapper."""
    123     if lambda_path.shape[0] > 2:
--> 124         lambda_0 = math.exp(2 * math.log(lambda_path[1]) - math.log(lambda_path[2]))
    125         lambda_path[0] = lambda_0
    126     return lambda_path

ValueError: math domain error
```

I guess there is an uncaught zero or -inf or something in the lambda_path, that is causing the math library to fail. Could you add a condtition?

**Comment by kcrum** [comment]
Thanks for reporting this @Visdoom. Could you please add a minimal working example that would produce such an error?

**Comment by Visdoom** [comment]
I will try to work on it

**Comment by kcrum** [comment]
Thank you!

**Comment by Visdoom** [comment]
Hey there, I found some examples that reliably reproduce that error in my code:

**Comment by Visdoom** [comment]
Other data would be:

**Comment by kcrum** [comment]
`glmnet.LogitNet` is expecting numbers for the dependent variable, not strings (or `np.object`s). You will want to cast your dependent variables to integers. For example:
```python
y = (y_train == 'DC').astype(int)
```
will set `'DC'` to `1` and everything else to `0`.

**Comment by Visdoom** [comment]
I do classification on a large scale and it works for most cases even though I use the dependent variable as it is. I don't think, that this is the problem.
If you want I can get an example with the same dependent variable that does the trick, so you can compare.
Best,
S.

**Comment by kcrum** [comment]
Huh, that's surprising. When I run the example you posted, it does raise the same "Math domain error," however when I replaced `y_train` with integers like I showed in my comment, the error goes away. Do you see the same thing?

**Comment by kcrum** [comment]
Hmmmm, now I'm starting to think the issue is something else. I'm guessing a number <= 0 is being passed to one of the `np.log` calls on line 124 in that last block of the traceback you posted. I'll reopen and investigate...

**Comment by Visdoom** [comment]
yes, when I replace the strings in `y_train` with `booleans` or `int` it works for me as well.

**Comment by kcrum** [comment]
It seems the third CV fold returns a lambda path mostly filled with zeros, and this is causing the error you're seeing. In this fold the covariates for the 'DC' class are effectively identical to those of the 'SC' class, so the best fit coefficient would be zero. Therefore it makes sense that the Fortran code would return a lambda path full of zeros, since no penalty is necessary to shrink the best fit coefficient of zero.

I don't know your use case, but as @wlattner mentioned to me offline, it typically doesn't make much sense to use glment in a univariate problem. It may be worthwhile to add a warning against the univariate case, but personally I don't think this issue merits any changes to python-glmnet, since it is the result of fairly pathological data that doesn't make for a well formed problem. 

I could be persuaded otherwise, however, so I'm curious to hear what you think. Thank you for filing issues here!

**Comment by Visdoom** [comment]
Hey @kcrum 

Thanks for investigating! I've encountered that error when searching a feature space automatically so it is indeed a rather seldom case. I agree that it does not make sense to use glmnet on uni variate cases but I personally are in favor of adding a warning, since those are better caught in an automated approach of i.e. feature selection with the goodness of fit being the selection criterion.
