### ISSUE TITLE
Compilation issue on MacOS

### ISSUE THREAD

**Issue by JWarmenhoven** [civisanalytics/python-glmnet#32]
I am running into a number of Fortran compilation issues on MacOS. I followed the installation instructions but when running `python setup.py install` I get the following warning: (repeated for many lines) 

```
glmnet/src/glmnet/glmnet5.f90:683:72:

       subroutine get_int_parms(sml,eps,big,mnlam,rsqmax,pmin,exmx)          772
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
```
After these, there are warnings about unused labels. 
At the end it returns an error.

```
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/usr/local/bin/gfortran -Wall -g -pie -headerpad_max_install_names build/temp.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/glmnet/_glmnetmodule.o build/temp.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/glmnet/fortranobject.o build/temp.macosx-10.9-x86_64-3.6/glmnet/src/glmnet/glmnet5.o -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.2.0 -lgfortran -o build/lib.macosx-10.9-x86_64-3.6/_glmnet.cpython-36m-darwin.so" failed with exit status 1
```
About about one and a half year ago I succesfully installed python-glmnet. Cannot remember any problems at that time. I am installing in a conda environment. Required packages scipy, numpy, scikit-learn have been installed. 
Any ideas?

**Comment by beckermr** [comment]
I don't know about these issues, but a conda package for this would probably be a good idea. 

Ignoring compiler warnings is not great practice, but also not crazy. Does the code actually compile? Does it ever throw an error, or do you just get warnings?

**Comment by JWarmenhoven** [comment]
Indeed, I forgot to mention that the package does not compile.

```
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/usr/local/bin/gfortran -Wall -g -pie -headerpad_max_install_names build/temp.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/glmnet/_glmnetmodule.o build/temp.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/build/src.macosx-10.9-x86_64-3.6/glmnet/fortranobject.o build/temp.macosx-10.9-x86_64-3.6/glmnet/src/glmnet/glmnet5.o -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.2.0 -lgfortran -o build/lib.macosx-10.9-x86_64-3.6/_glmnet.cpython-36m-darwin.so" failed with exit status 1
```

**Comment by JWarmenhoven** [comment]
I will try installing with conda-forge:
https://github.com/conda-forge/glmnet-feedstock

**Comment by beckermr** [comment]
Ahhh cool. I did not know that existed!

**Comment by JWarmenhoven** [comment]
I did not either until today. 
It installs in the correct conda environment...
```
$ conda list | grep glm
glmnet                    2.0.0                   np113_0    conda-forge
```
...but I cannot import the glmnet module. 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-35-52c1c0e49750> in <module>()
----> 1 import glmnet as gln

ModuleNotFoundError: No module named 'glmnet'
```

**Comment by beckermr** [comment]
I am getting this too. It looks like it is installing the libs to the python 2.7 site packages directory instead of 3.6 for me. 

```
$ ls miniconda3/envs/civis/lib/python2.7/site-packages/
_glmnet.so              glmnet/                 glmnet-2.0.0.dist-info/ 
```

**Comment by beckermr** [comment]
I made an issue upstream - https://github.com/conda-forge/glmnet-feedstock/issues/3.

Looking at the conda package, I cannot divine why...

**Comment by JWarmenhoven** [comment]
Yep...same here. (ends up in python 2.7 site-packages )

**Comment by beckermr** [comment]
Cool. I put in a fix to the conda package. Hopefully it gets merged soon.

**Comment by beckermr** [comment]
The new conda forge package has merged. I am closing this. If you still have trouble, please feel free to open an issue here or on the conda forge feedstock!

**Comment by edoroth** [comment]
I still have an issue importing glmnet. Conda is installing correctly into python 3.8 packages, but I can't understand why it isn't able to import... there is a glymnet.py file inside of the glmnet_python folder which was installed

**Comment by drealtoni** [comment]
@edoroth were you able to get a solution to this
