### ISSUE TITLE
Update repo metadata

### ISSUE THREAD

**Issue by wlattner** [civisanalytics/python-glmnet#37]
GitHub shows this as a Fortran repo:
<img width="183" alt="screen shot 2018-02-20 at 8 46 33 pm" src="https://user-images.githubusercontent.com/903096/36463528-6329862c-167f-11e8-82dc-fd835a0a4e01.png">

Some tags would be cool too.

**Comment by stephen-hoover** [comment]
With PR #57 , this repo is now detected as 100% Python. We're tagged with the six tags lasso, elasticnet, glmnet, glm, r, and python.
