### ISSUE TITLE
Create new release for PIP past 2.0

### ISSUE THREAD

**Issue by ericjster** [civisanalytics/python-glmnet#49]
Please consider creating a new release for PIP (after 2.0).
There are some great new features added after release 2.0, including issue #40, #41 lower_limit and upper_limit, and #31 max_features.

**Comment by stephen-hoover** [comment]
Thank you for flagging this! You're right, it's time for a v2.1 release. Let's aim for this week or next week.

**Comment by stephen-hoover** [comment]
@ericjster , we now have a v2.1.1 release on PyPI and conda-forge (for OS X and Linux). Thank you for opening this issue!

New features and fixes in v2.1: https://github.com/civisanalytics/python-glmnet/releases/tag/v2.1.0
