### ISSUE TITLE
Where to put 'lambda.1se'

### ISSUE THREAD

**Issue by lingling93** [civisanalytics/python-glmnet#60]
I want to use 'lambda.1se' to choose the model, I didn't find which parameter is for it.
Can you help me with that ?
Thank you!

**Comment by wlattner** [comment]
The parameter named `cut_point` determines how lambda is selected. By default, `cut_point = 1`, following the "one standard error rule." After the model is fitted, the selected value of lambda is saved to the attribute named `lambda_best_`.  So if you are coming from R and `cv.glmnet`, `lambda_best_` in this implementation is analogous to `lambda.1se`.

**Comment by stephen-hoover** [comment]
Thank you, @wlattner ! @lingling93 , does that answer your question?

**Comment by lingling93** [comment]
@wlattner @stephen-hoover  Perfect answer! Thank you.
