### ISSUE TITLE
Use external joblib and six packages, instead of sklearn.externals versions

### ISSUE THREAD

**Issue by trimeta** [civisanalytics/python-glmnet#61]
Starting in version 0.21 of sklearn, certain packages previously provided in the sklearn.externals module are now depreciated. These include joblib and six, which glmnet uses in its util.py and scorer.py files, respectively. To reduce FutureWarnings upon module load, and also to avoid issues when sklearn-0.23 is released and suddenly joblib and six aren't found under sklearn.externals, it would be a good idea to depend on these packages directly, adding them to the requirements.txt file.

**Comment by trimeta** [comment]
I was about to post a nasty comment about how this Issue is still open over a month after May 12th, when sklearn-0.23.0 was released and broke the existing version of glmnet, but then I noticed that commits https://github.com/civisanalytics/python-glmnet/commit/b26cca2ee731dd8f5674226d6b4a5457e53aca6a and https://github.com/civisanalytics/python-glmnet/commit/ca24c77c108443da816efb2252a7b885bebe2ba2 address this Issue. So my real question is, when will a new release be pushed to incorporate these commits?

**Comment by mheilman** [comment]
I think it should be possible to make a new release in the next week or two.

Thank you for filing this issue.
